export interface Rank {
  id: string
  name: string
  prefix: string
  color: string
  gradientFrom: string
  gradientTo: string
  price: {
    bdt: number
    inr: number
    usd: number
  }
  claimBlocks: string
  maxHomes: number
  maxAuctions: number
  features: string[]
  kitItems: string[]
  duration: string
}

export const ranks: Rank[] = [
  {
    id: 'dedliest',
    name: 'DEDLIEST',
    prefix: 'DEDLIEST',
    color: 'from-red-600 to-orange-500',
    gradientFrom: '#dc2626',
    gradientTo: '#f97316',
    price: { bdt: 2199, inr: 1799, usd: 18.89 },
    claimBlocks: '30k',
    maxHomes: 12,
    maxAuctions: 20,
    features: [
      'Access To /feed (Feed every 5m min)',
      'Access To /sit, /crawl, /lay (Sit, Lay and Crawl)',
      'Access To /craft (Crafting)',
      'Access To /grindstone (Grindstone)',
      'Access To /trash (Disposing)',
      'Access To /loom (Looming)',
      'Access To /anvil (Opens Anvil)',
      'Access To /recipe (Show Item Recipe)',
      'Access To /back (Tp Back To Previous Place)',
      'Access To /cartable (Cartography Table)',
      '/Fly Command Use + speed control',
    ],
    kitItems: [
      'Super custom gear unbreakable enchant (armor/tools/bow/mace/trident)',
      '1 Mace 2 Trident full (super custom enchant)',
      '200 Golden Apple + 100 Enchanted Golden Apple',
      '100 Golden Carrot',
      '40 Cow, 40 Chicken, 7 Evoker, 20 Skeleton, 20 Creeper Spawner',
      'Unbreakable 2 Elytra with all full enchant',
      'Any small house schematica places',
    ],
    duration: 'Valid for the current season of KILLERMC',
  },
  {
    id: 'elvion',
    name: 'ELVION',
    prefix: 'ELVION',
    color: 'from-purple-600 to-pink-500',
    gradientFrom: '#9333ea',
    gradientTo: '#ec4899',
    price: { bdt: 1399, inr: 1199, usd: 11.49 },
    claimBlocks: '20k',
    maxHomes: 12,
    maxAuctions: 15,
    features: [
      'Access To /feed (Feed every 10m min)',
      'Access To /sit, /crawl, /lay (Sit, Lay and Crawl)',
      'Access To /craft (Crafting)',
      'Access To /grindstone (Grindstone)',
      'Access To /trash (Disposing)',
      'Access To /loom (Looming)',
      'Access To /anvil (Opens Anvil)',
      'Access To /recipe (Show Item Recipe)',
      'Access To /back (Tp Back To Previous Place)',
      'Access To /cartable (Cartography Table)',
      '/Fly Command Use + speed control',
    ],
    kitItems: [
      'Full Ultra max-custom gear custom enchant (armor/tools/bow/trident/mace)',
      '1 Mace 2 Trident full (custom enchant)',
      '64 Golden Apple + 25 Enchanted Golden Apple',
      '100 Golden Carrot',
      '30 Cow, 20 Chicken, 3 Evoker, 7 Skeleton, 4 Creeper Spawner',
      '02 Unbreakable elytra with all full enchant',
      'Any small house schematica places',
    ],
    duration: 'Valid for the current season of KILLERMC',
  },
  {
    id: 'eternal',
    name: 'ETERNAL',
    prefix: 'ETERNAL',
    color: 'from-amber-500 to-yellow-400',
    gradientFrom: '#f59e0b',
    gradientTo: '#facc15',
    price: { bdt: 999, inr: 799, usd: 8.50 },
    claimBlocks: '16k',
    maxHomes: 10,
    maxAuctions: 12,
    features: [
      'Access To /feed (Feed every 20 min)',
      'Access To /sit, /crawl, /lay (Sit, Lay and Crawl)',
      'Access To /craft (Crafting)',
      'Access To /grindstone (Grindstone)',
      'Access To /trash (Disposing)',
      'Access To /loom (Looming)',
      'Access To /anvil (Opens Anvil)',
      'Access To /back (Tp Back To Previous Place)',
      'Access To /cartable (Cartography Table)',
      '/Fly Command Use',
    ],
    kitItems: [
      'Full max-custom gear (custom enchant) (armor/tools)(bow custom enchant)',
      '1 Mace 2 Trident full (vanilla enchant)',
      '02 Elytra Full Enchant',
      '25 Shulker',
      '50 Golden Apple + 15 Enchanted Golden Apple',
      '70 Golden Carrot',
      '20 Cow, 10 Chicken and 1 Evoker Spawner',
      'Any small house schematica places',
    ],
    duration: 'Valid for the current season of KILLERMC',
  },
  {
    id: 'imortal',
    name: 'IMORTAL',
    prefix: 'IMORTAL',
    color: 'from-cyan-500 to-blue-500',
    gradientFrom: '#06b6d4',
    gradientTo: '#3b82f6',
    price: { bdt: 649, inr: 499, usd: 5.49 },
    claimBlocks: '12k',
    maxHomes: 10,
    maxAuctions: 12,
    features: [
      'Access To /feed (Feed every 20 min)',
      'Access To /sit, /crawl, /lay (Sit, Lay and Crawl)',
      'Access To /craft (Crafting)',
      'Access To /grindstone (Grindstone)',
      'Access To /trash (Disposing)',
      'Access To /loom (Looming)',
      'Access To /anvil (Opens Anvil)',
      'Access To /back (Tp Back To Previous Place)',
      'Access To /cartable (Cartography Table)',
    ],
    kitItems: [
      'Netherite Full max-custom gear (custom enchant) (armor/tools)',
      '1 Mace and 1 Trident (vanilla enchant)',
      'Bow (custom enchant)',
      '10 Shulker',
      '40 Golden Apple + 7 Enchanted Golden Apple',
      '50 Golden Carrot',
      '13 Cow Spawner',
    ],
    duration: 'Valid for the current season of KILLERMC',
  },
  {
    id: 'lord',
    name: 'LORD',
    prefix: 'LORD',
    color: 'from-violet-600 to-indigo-500',
    gradientFrom: '#7c3aed',
    gradientTo: '#6366f1',
    price: { bdt: 449, inr: 369, usd: 3.89 },
    claimBlocks: '7k',
    maxHomes: 6,
    maxAuctions: 9,
    features: [
      'Access To /sit, /crawl, /lay (Sit, Lay and Crawl)',
      'Access To /craft (Crafting)',
      'Access To /grindstone (Grindstone)',
      'Access To /trash (Disposing)',
      'Access To /loom (Looming)',
      'Access To /back (Tp Back To Previous Place)',
      'Access To /cartable (Cartography Table)',
    ],
    kitItems: [
      'Full max Diamond Armor (custom enchant)',
      'Vanilla enchant tools',
      '5 Shulker',
      '30 Golden Apple + 5 Enchanted Golden Apple',
      '8 Chicken Spawners',
    ],
    duration: 'Valid for the current season of KILLERMC',
  },
  {
    id: 'titan',
    name: 'TITAN',
    prefix: 'TITAN',
    color: 'from-emerald-500 to-green-500',
    gradientFrom: '#10b981',
    gradientTo: '#22c55e',
    price: { bdt: 249, inr: 199, usd: 2.10 },
    claimBlocks: '5k',
    maxHomes: 4,
    maxAuctions: 7,
    features: [
      'Access To /sit, /crawl, /lay (Sit, Lay and Crawl)',
      'Access To /craft (Crafting)',
      'Access To /trash (Disposing)',
      'Access To /loom (Looming)',
      'Access To /cartable (Cartography Table)',
    ],
    kitItems: [
      'Netherite Max armor + tools (vanilla enchant)',
      '3 Shulker',
      '20 Golden Apple + 1 Enchanted Golden Apple',
      '5 Skeleton Spawner',
    ],
    duration: 'Valid for the current season of KILLERMC',
  },
  {
    id: 'knight',
    name: 'KNIGHT',
    prefix: 'KNIGHT',
    color: 'from-slate-500 to-slate-400',
    gradientFrom: '#64748b',
    gradientTo: '#94a3b8',
    price: { bdt: 179, inr: 149, usd: 1.49 },
    claimBlocks: '2k',
    maxHomes: 3,
    maxAuctions: 5,
    features: [
      'Access To /sit, /crawl, /lay (Sit, Lay and Crawl)',
      'Access To /craft (Crafting)',
      'Access To /trash (Disposing)',
    ],
    kitItems: [
      'Diamond Max armor + tools (vanilla enchant)',
      '2 Shulker',
      '2 Skeleton Spawner',
      '10 Golden Apple',
    ],
    duration: 'Valid for the current season of KILLERMC',
  },
]
